### ISSUE TITLE
[EPIC] Implement user-microservice functional

### ISSUE THREAD

**Issue by MaksimPegov** [MaksimPegov/todo-service#5]
1. Registration #8 
2. Login #9 
3. Delete user #10 
4. Edit user data #11 
5. Get user #12

**Comment by antonpegov** [comment]
This task is massive. Pls divide it to small sub-tasks. I propose to try the approach tht we use in ZP: 

> [ EPIC 1] (some mega-feature like 'Implement user-microservice functional')

-     [ FEATURE 1 ]

     - API TASK 1 
     -  API TASK 2
     - UI TASK 1
     - TESTING TASK (Test how it all works togather)

-     [ FEATURE 2 ]
     -  API TASK 1 
     - UI TASK 1
     - UI TASK 2
     - TESTING TASK (Test how it all works togather)


> [ EPIC 2]
..........

**Comment by MaksimPegov** [comment]
> This task is massive. Pls divide it to small sub-tasks. I propose to try the approach tht we use in ZP:
> 
> > [ EPIC 1] (some mega-feature like 'Implement user-microservice functional')
> 
> * ```
>   [ FEATURE 1 ]
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   
>   * API TASK 1
>   * API TASK 2
>   * UI TASK 1
>   * TESTING TASK (Test how it all works togather)
> * ```
>   [ FEATURE 2 ]
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   
>   * API TASK 1
>   * UI TASK 1
>   * UI TASK 2
>   * TESTING TASK (Test how it all works togather)
> 
> > [ EPIC 2]
> > ..........

ok
